# Generated by Django 5.1.6 on 2025-03-04 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Reporte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                ("titulo", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
            ],
            options={
                "verbose_name": "Reporte",
                "verbose_name_plural": "Reportes",
                "db_table": "reportes",
                "ordering": ["fecha_creacion"],
            },
        ),
    ]
