# Generated by Django 5.1.6 on 2025-02-28 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reportes", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reporte",
            options={
                "ordering": ["fecha_creacion"],
                "verbose_name": "Reporte",
                "verbose_name_plural": "Reportes",
            },
        ),
        migrations.RenameField(
            model_name="reporte",
            old_name="id_usuario",
            new_name="usuario",
        ),
        migrations.AlterModelTable(
            name="reporte",
            table="reportes",
        ),
    ]
