# Generated by Django 5.1.5 on 2025-03-14 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='descripcion',
            field=models.TextField(max_length=500),
        ),
    ]
