# Generated by Django 5.1.6 on 2025-03-01 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usuario",
            options={"verbose_name": "Usuario", "verbose_name_plural": "Usuarios"},
        ),
        migrations.AlterModelTable(
            name="usuario",
            table="usuario",
        ),
    ]
