from django.urls import path
from .views import (listar_proyectos_page_view,
                    listar_proyectos_ajax_view,
                    crear_proyecto_ajax_view,
                    eliminar_proyecto_ajax_view,
                    actualizar_proyecto_ajax_view,
                    crear_pizarra_ajax_view,
                    actualizar_pizarra_ajax_view,
                    eliminar_pizarra_ajax_view,
                    listar_notas_page_view,
                    crear_nota_ajax_view,
                    eliminar_nota_ajax_view,
                    listar_notas_ajax_view,
                    obtener_nota_ajax_view,
                    crear_comentario_ajax_view,
                    obtener_comentarios_ajax_view

                    )
urlpatterns = [
    path('',
         listar_proyectos_page_view,
         name='listar_proyectos_page'),
    path('ajax/crear-proyecto',
         crear_proyecto_ajax_view,
         name='crear_proyecto_ajax_view'
         ),
    path('ajax/eliminar-proyecto',
         eliminar_proyecto_ajax_view,
         name='eliminar_proyecto_ajax_view'
         ),
    path('ajax/actualizar-proyecto',
         actualizar_proyecto_ajax_view,
         name='actualizar_proyecto_ajax_view'
         ),
    path('ajax/listar-proyectos/',
         listar_proyectos_ajax_view,
         name='listar_proyectos_ajax_view'
         ),
    path('ajax/crear-pizarra',
         crear_pizarra_ajax_view,
         name='crear_pizarra_ajax_view'
         ),
    path('ajax/actualizar-pizarra',
         actualizar_pizarra_ajax_view,
         name='actualizar_pizarra_ajax_view'
         ),
    path('ajax/eliminar-pizarra',
         eliminar_pizarra_ajax_view,
         name='eliminar_pizarra_ajax_view'
         ),
    path('listar-notas/<int:pizarra_id>',
         listar_notas_page_view,
         name='listar_notas_page'
         ),
    path('ajax/crear-nota',
         crear_nota_ajax_view,
         name='crear_nota_ajax_view'
         ),
    path('ajax/eliminar-nota',
         eliminar_nota_ajax_view,
         name='eliminar_nota_ajax_view'),
    path('ajax/listar-notas/<int:pizarra_id>',
         listar_notas_ajax_view,
         name='listar_notas_ajax_view'
         ),
    path('ajax/obtener-nota/<int:nota_id>',
         obtener_nota_ajax_view,
         name='obtener_nota_ajax_view'
         ),
    path(
        'ajax/listar-comentarios/<int:nota_id>',
        obtener_comentarios_ajax_view,
        name='obtener_comentarios_ajax_view'
    ),
    path('ajax/crear-comentario',
         crear_comentario_ajax_view,
         name='crear_notas_ajax_view'),
]
