# Generated by Django 5.1.6 on 2025-02-27 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Etiqueta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=100)),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("#FF5733", "Rojo"),
                            ("#33FF57", "Verde"),
                            ("#3357FF", "Azul"),
                            ("#F4D03F", "Amarillo"),
                            ("#8E44AD", "Morado"),
                            ("#2C3E50", "Negro"),
                        ],
                        default="#FF5733",
                        max_length=7,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Nota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                ("titulo", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
                ("estado", models.BooleanField(default=False)),
                (
                    "id_etiqueta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="proyectos.etiqueta",
                    ),
                ),
                (
                    "id_usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="Comentario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                ("descripcion", models.TextField()),
                (
                    "imagen",
                    models.ImageField(blank=True, null=True, upload_to="imagenes/"),
                ),
                (
                    "id_usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "id_nota",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="proyectos.nota"
                    ),
                ),
            ],
            options={
                "ordering": ["fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="Archivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                ("archivo", models.FileField(upload_to="archivos/")),
                (
                    "id_usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "id_nota",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="proyectos.nota"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Pizarra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=100)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "id_usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["fecha_creacion"],
            },
        ),
        migrations.AddField(
            model_name="nota",
            name="id_pizarra",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="proyectos.pizarra"
            ),
        ),
        migrations.CreateModel(
            name="Proyecto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
                ("fecha_inicio", models.DateTimeField(blank=True, null=True)),
                ("fecha_entrega", models.DateTimeField(blank=True, null=True)),
                (
                    "id_usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["fecha_creacion"],
            },
        ),
        migrations.AddField(
            model_name="pizarra",
            name="id_proyecto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="proyectos.proyecto"
            ),
        ),
    ]
