# Generated by Django 5.1.6 on 2025-03-04 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Archivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "archivo",
                    models.FileField(blank=True, null=True, upload_to="archivos/"),
                ),
            ],
            options={
                "verbose_name": "Archivo",
                "verbose_name_plural": "Archivos",
                "db_table": "archivos",
            },
        ),
        migrations.CreateModel(
            name="Comentario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                ("descripcion", models.TextField()),
                (
                    "imagen",
                    models.ImageField(blank=True, null=True, upload_to="imagenes/"),
                ),
            ],
            options={
                "verbose_name": "Comentario",
                "verbose_name_plural": "Comentarios",
                "db_table": "comentarios",
                "ordering": ["fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="Etiqueta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=100)),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("#FF5733", "Rojo"),
                            ("#33FF57", "Verde"),
                            ("#3357FF", "Azul"),
                            ("#F4D03F", "Amarillo"),
                            ("#8E44AD", "Morado"),
                            ("#2C3E50", "Negro"),
                        ],
                        default="#FF5733",
                        max_length=7,
                    ),
                ),
            ],
            options={
                "verbose_name": "Etiqueta",
                "verbose_name_plural": "Etiquetas",
                "db_table": "etiquetas",
            },
        ),
        migrations.CreateModel(
            name="Nota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                ("titulo", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
                ("estado", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Nota",
                "verbose_name_plural": "Notas",
                "db_table": "notas",
                "ordering": ["fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="Pizarra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Pizarra",
                "verbose_name_plural": "Pizarras",
                "db_table": "pizarras",
                "ordering": ["fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="Proyecto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
                ("fecha_inicio", models.DateTimeField(blank=True, null=True)),
                ("fecha_entrega", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Proyecto",
                "verbose_name_plural": "Proyectos",
                "db_table": "proyectos",
                "ordering": ["fecha_creacion"],
            },
        ),
    ]
