# Generated by Django 5.1.6 on 2025-03-10 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proyectos", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="nota",
            name="pendiente",
            field=models.DateField(
                blank=True, help_text="Fecha límite para la nota", null=True
            ),
        ),
    ]
