# Generated by Django 5.1.6 on 2025-03-11 20:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proyectos", "0003_nota_pendiente"),
    ]

    operations = [
        migrations.AddField(
            model_name="etiqueta",
            name="seleccionada",
            field=models.BooleanField(
                default=False,
                help_text="Indica si la etiqueta está seleccionada para una nota",
            ),
        ),
        migrations.AlterField(
            model_name="nota",
            name="pendiente",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 3, 11, 20, 22, 41, 911853, tzinfo=datetime.timezone.utc
                ),
                help_text="Fecha límite para la nota",
            ),
            preserve_default=False,
        ),
    ]
