# Generated by Django 5.1.6 on 2025-03-11 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proyectos", "0004_etiqueta_seleccionada_alter_nota_pendiente"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nota",
            name="etiqueta",
        ),
        migrations.AddField(
            model_name="nota",
            name="color",
            field=models.CharField(
                choices=[
                    ("#FF5733", "Rojo"),
                    ("#33FF57", "Verde"),
                    ("#3357FF", "Azul"),
                    ("#F4D03F", "Amarillo"),
                    ("#8E44AD", "Morado"),
                    ("#2C3E50", "Negro"),
                ],
                default="#FF5733",
                max_length=7,
            ),
        ),
        migrations.DeleteModel(
            name="Etiqueta",
        ),
    ]
