# Generated by Django 5.1.6 on 2025-03-14 22:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proyectos", "0005_remove_nota_etiqueta_nota_color_delete_etiqueta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proyecto",
            name="fecha_entrega",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="proyecto",
            name="fecha_inicio",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
