# Generated by Django 5.1.6 on 2025-03-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proyectos", "0006_alter_proyecto_fecha_entrega_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nota",
            name="color",
            field=models.CharField(
                choices=[
                    ("#F7C8D3", "Rosado"),
                    ("#FFD8B1", "Naranja"),
                    ("#B8E6C9", "Verde"),
                    ("#FCEFB4", "Amarillo"),
                    ("#D7C3FF", "Morado"),
                    ("#BEE3F8", "Celeste"),
                ],
                default="#FF5733",
                max_length=7,
            ),
        ),
    ]
